name: Build & Deploy Fullstack

on:
  push:
    branches:
      - production
  workflow_dispatch:

jobs:
  frontend:
    name: Build & Deploy Angular 21 Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "24.12.0"

      - name: Install dependencies (frontend)
        run: npm install
        working-directory: ./frontend

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Build Angular frontend
        run: ng build --configuration production
        working-directory: ./frontend

      - name: Deploy frontend
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: frontend/dist/frontend
          github-token: ${{ secrets.GITHUB_TOKEN }}

  backend:
    name: Deploy NestJs Backend
    runs-on: ubuntu-latest
    needs: frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "24.12.0"

      - name: Install dependencies (backend)
        run: npm install
        working-directory: ./backend

      - name: Build NestJs backend
        run: npm run build
        working-directory: ./backend

      - name: Deploy backend via SSH
        uses: easingthemes/ssh-deploy@v2
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
